spring.sql.init.enabled=true
spring.sql.init.platform=postgresql
spring.datasource.platform=postgresql

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5431}/vms_ac_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:ENC(aHGDu03/MzCmTcoeucsX+MOl5vIigjodesGDmgWIPqOkD6kMj9pBs/Kxwv0prq+7)}

spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jasypt.encryptor.password=${SECRET_ENCRYPTION_KEY}

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
