INSERT INTO credentialType VALUES ('1','Card','RFID Card',false);
INSERT INTO credentialType VALUES ('2','Face','Face Recognition',false);
INSERT INTO credentialType VALUES ('3','Fingerprint','Fingerprint scanner',false);
INSERT INTO credentialType VALUES ('4','Pin','Digit Pin',false);

INSERT INTO AuthMethod VALUES ('1','Card','AND',null,false);
INSERT INTO AuthMethod VALUES ('2','Face','AND',null,false);
INSERT INTO AuthMethod VALUES ('3','FingerPrint','AND',null,false);
INSERT INTO AuthMethod VALUES ('4','Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('5','Card + Face','AND',null,false);
INSERT INTO AuthMethod VALUES ('6','Card / Face','OR',null,false);
INSERT INTO AuthMethod VALUES ('7','Card + FingerPrint','AND',null,false);
INSERT INTO AuthMethod VALUES ('8','Card / FingerPrint','OR',null,false);
INSERT INTO AuthMethod VALUES ('9','Card + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('10','Face + FingerPrint','AND',null,false);
INSERT INTO AuthMethod VALUES ('11','Face / FingerPrint','OR',null,false);
INSERT INTO AuthMethod VALUES ('12','Face + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('13','FingerPrint + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('14','Card + Face + FingerPrint','AND',null,false);
INSERT INTO AuthMethod VALUES ('15','Card / Face / FingerPrint','OR',null,false);
INSERT INTO AuthMethod VALUES ('16','Card + Face + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('17','Card + FingerPrint + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('18','Face + FingerPrint + Pin','AND',null,false);
INSERT INTO AuthMethod VALUES ('19','Card + Face + FingerPrint + Pin','AND',null,false);

INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('1','1','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('2','2','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('3','3','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('4','4','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('5','5','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('6','5','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('7','6','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('8','6','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('9','7','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('10','7','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('11','8','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('12','8','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('13','9','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('14','9','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('15','10','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('16','10','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('17','11','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('18','11','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('19','12','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('20','12','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('21','13','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('22','13','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('23','14','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('24','14','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('25','14','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('26','15','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('27','15','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('28','15','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('29','16','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('30','16','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('31','16','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('32','17','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('33','17','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('34','17','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('35','18','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('36','18','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('37','18','4',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('38','19','1',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('39','19','2',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('40','19','3',false);
INSERT INTO AuthMethodCredentialTypeNtoN VALUES ('41','19','4',false);

INSERT INTO EventActionInputType VALUES ('1','AUTHENTICATED SCAN', false, null);
INSERT INTO EventActionInputType VALUES ('2','UNAUTHENTICATED SCAN', false, null);
INSERT INTO EventActionInputType VALUES ('3','EXIT BUTTON PRESSED', false, null);
INSERT INTO EventActionInputType VALUES ('4','DOOR OPENED WITHOUT AUTHENTICATION', true, null);
INSERT INTO EventActionInputType VALUES ('5','DOOR OPENED WITH AUTHENTICATION', true, null);
INSERT INTO EventActionInputType VALUES ('6','FIRE', false, null);
INSERT INTO EventActionInputType VALUES ('7','GEN_IN_1', false, null);
INSERT INTO EventActionInputType VALUES ('8','GEN_IN_2', false, null);
INSERT INTO EventActionInputType VALUES ('9','GEN_IN_3', false, null);
INSERT INTO EventActionInputType VALUES ('10','DOOR CLOSED', false, null);

INSERT INTO EventActionOutputType VALUES ('1','GEN_OUT_1', true, null);
INSERT INTO EventActionOutputType VALUES ('2','GEN_OUT_2', true, null);
INSERT INTO EventActionOutputType VALUES ('3','GEN_OUT_3', true, null);
INSERT INTO EventActionOutputType VALUES ('4','UNLOCK DOOR', false, null);
INSERT INTO EventActionOutputType VALUES ('5','BUZZER', true, null);
INSERT INTO EventActionOutputType VALUES ('6','LED', true, null);
INSERT INTO EventActionOutputType VALUES ('7','NOTIFICATION (SMS)', false, null);
INSERT INTO EventActionOutputType VALUES ('8','NOTIFICATION (EMAIL)', false, null);

INSERT INTO EventActionType VALUES ('1','Authenticated Scans', false);
INSERT INTO EventActionType VALUES ('2','Masterpassword used', false);
INSERT INTO EventActionType VALUES ('3','UnAuthenticated Scans', false);
INSERT INTO EventActionType VALUES ('4','Door Opened', false);
INSERT INTO EventActionType VALUES ('5','Door Closed', false);
INSERT INTO EventActionType VALUES ('6','Warning : Door Opened without authorisation', false);
INSERT INTO EventActionType VALUES ('7','Buzzer Started buzzing', false);
INSERT INTO EventActionType VALUES ('8','Buzzer Stopped buzzing', false);
INSERT INTO EventActionType VALUES ('9','Push Button pressed', false);
INSERT INTO EventActionType VALUES ('10','GEN_IN_1 detected', false);
INSERT INTO EventActionType VALUES ('11','GEN_IN_2 detected', false);
INSERT INTO EventActionType VALUES ('12','GEN_IN_3 detected', false);
INSERT INTO EventActionType VALUES ('13','Valid PIN used', false);
INSERT INTO EventActionType VALUES ('14','Invalid PIN used', false);

